title: Michael's Motive
tagline: Living is easy with eyes closed
description: Welcome to my little corner of the Internet.
url: https://micmax.pw

author:
  name: Michael Maxwell
  email: yo@micmax.pw

locale: en_CA
permalink: /:year/:month/:day/:title
rss: RSS Feed
theme: minima
show_excerpts: true
google_analytics: UA-55845382-5

plugins:
  - jekyll-feed

minima:
  skin: dark

  social_links:
    github: mic-max
    instagram: micmax_
    keybase: micmax
    linkedin: micmax
    twitter: micmax_
# discord_username: Lemur#6826
# slippi_username: MM#421
# steam_friend_code: 138017094
# twitch_username: ProLemur
# youtube_username: ThePR0Lemur
# venmo_username: micmax
