title: Michael's Motive
tagline: Living is easy with eyes closed
description: Welcome to my little corner of the Internet. Living is easy with eyes closed. They made me do it.
url: https://micmax.pw
permalink: /:year/:month/:day/:title

author:
  name: Michael Maxwell
  email: yo@micmax.pw

google_analytics: UA-55845382-5
show_excerpts: true
theme: minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: jekyll/minima

minima:
  skin: dark

  social_links:
    github: mic-max
    instagram: micmax_
    keybase: micmax
    linkedin: micmax
    twitter: micmax_
    youtube: ThePR0Lemur
    # discord: Lemur#6826
    # slippi: MM#421
    # steam: 138017094
    # twitch: ProLemur
    # venmo: micmax
