title: Michael's Motive
tagline: Living is easy with eyes closed
description: Welcome to my little corner of the Internet.
url: https://micmax.pw

author:
  name: Michael Maxwell
  email: yo@micmax.pw

locale: en_CA
permalink: /:year/:month/:day/:title
rss: RSS Feed
theme: minima
show_excerpts: true
google_analytics: UA-55845382-5

plugins:
  - jekyll-feed

minima:
  skin: dark

  social_links:
    github: mic-max
    instagram: micmax_
    keybase: micmax
    linkedin: micmax
    twitter: micmax_
    # discord: Lemur#6826
    # slippi: MM#421
    # steam: 138017094
    # twitch: ProLemur
    # youtube: ThePR0Lemur
    # venmo: micmax
