title: Michael's Motive
tagline: Living is easy with eyes closed
description: Welcome to my little corner of the Internet. Living is easy with eyes closed. They made me do it.
url: https://micmax.pw
permalink: /:year/:month/:day/:title
# permalink: /:category/:title
locale: en_CA
highlighter: rouge
timezone: America/Los_Angeles

logo: /assets/micmax.pw

author:
  name: Michael Maxwell
  email: yo@micmax.pw

google_analytics: UA-55845382-5
bing-verify: 
show_excerpts: true
theme: minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

remote_theme: jekyll/minima

exclude:
  - CNAME
  - README.md
  - assets/temp

minima:
  skin: dark

  social_links:
    github: mic-max
    instagram: micmax_
    keybase: micmax
    linkedin: micmax
    twitter: micmax_
    youtube: ThePR0Lemur
    flickr: micmax_
    # discord: Lemur#6826
    # slippi: MM#421
    # steam: 138017094
    # twitch: ProLemur
    # venmo: micmax
