title: Michael's Motive
tagline: Living is easy with eyes closed
description: Welcome to my little corner of the Internet. Living is easy with eyes closed. They made me do it.
url: https://micmax.pw
permalink: /:title
locale: en_CA
highlighter: rouge
timezone: America/Los_Angeles

logo: /assets/micmax.pw

author:
  name: Michael Maxwell
  email: yo@micmax.pw
  twitter: micmax_

webmaster_verification:
  google: 1234

google_analytics: UA-55845382-5
bing-verify: 
show_excerpts: true

header_pages:
  - whoami.md
  - cv.md
  - art.md
  - models.md
  - lyrics.md

exclude:
  - CNAME
  - README.md
  - comments.md
  - assets/cad/

collections:
  art:
    output: true
  models:
    output: true
  lyrics:
    output: true

# Plugins Installed

plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Plugin Configuration

jekyll-mentions: https://twitter.com

jekyll_compose:
  auto_open: true
  # default_front_matter:
    # drafts:
      # description:
      # image: assets/img/
      # category:
      # tags:

# Theme Configuration

remote_theme: jekyll/minima@6513ea8b9c1c4909b6aa79926d52a1f7d865c5e7
minima:
  skin: dark

  social_links:
    github: mic-max
    instagram: micmax_
    keybase: micmax
    linkedin: micmax
    twitter: micmax_
    youtube: ThePR0Lemur # https://youtube.com/@micmax
    flickr: 194469094@N02
    # discord: Lemur#6826
    # slippi: MM#421
    # steam: 138017094
    # twitch: ProLemur
    # venmo: micmax
    # thingiverse: micmax
    # chess: micmax
    # spotify: https://open.spotify.com/user/22vaj64qyjza6bhfm62alvdui
